#!/bin/zsh

# 🏥 HEALTHCARE APP - MANUAL STARTUP
# Run each command in a SEPARATE terminal window

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🏥 HEALTHCARE APPLICATION - STARTUP INSTRUCTIONS        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "YOU NEED TO OPEN 2 TERMINAL WINDOWS"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 TERMINAL WINDOW 1 - BACKEND SERVER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Copy and paste this command:"
echo ""
echo "cd /Users/mrdevsharma/Downloads/EX/healthcare-prototype/server && node index.js"
echo ""
echo "You should see:"
echo "  ✅ MongoDB connected successfully"
echo "  🚀 Server running on port 3001"
echo ""
echo "⚠️  KEEP THIS WINDOW OPEN!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 TERMINAL WINDOW 2 - FRONTEND APP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Copy and paste this command:"
echo ""
echo "cd /Users/mrdevsharma/Downloads/EX/healthcare-prototype && npm start"
echo ""
echo "Wait ~30 seconds. Browser will auto-open to:"
echo "  🌐 http://localhost:3000"
echo ""
echo "⚠️  KEEP THIS WINDOW OPEN TOO!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 LOGIN CREDENTIALS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Admin:   admin@hospital.com / admin123"
echo "Patient: +1234567890 / OTP: 123456"
echo "Doctor:  doctor@hospital.com / doctor123"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
