import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { Prescription, Patient, Doctor } from '../types';

export interface DigitalSignature {
  doctorName: string;
  licenseNumber: string;
  signatureDate: string;
  digitalCertificate?: string;
}

export class PrescriptionPDFGenerator {
  private static readonly LOGO_TEXT = 'LuminaX-alt';
  private static readonly HEADER_COLOR = '#1e40af';
  private static readonly TEXT_COLOR = '#374151';
  private static readonly ACCENT_COLOR = '#ef4444';

  static async generatePrescriptionPDF(
    prescription: Prescription,
    patient: Patient,
    doctor: Doctor,
    signature?: DigitalSignature
  ): Promise<void> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.width;
    const pageHeight = pdf.internal.pageSize.height;
    const margin = 20;
    let yPosition = margin;

    // Helper function to add text with automatic line wrapping
    const addText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 10) => {
      pdf.setFontSize(fontSize);
      const lines = pdf.splitTextToSize(text, maxWidth);
      pdf.text(lines, x, y);
      return y + (lines.length * (fontSize * 0.4));
    };

    try {
      // Header
      this.addHeader(pdf, pageWidth, margin, yPosition);
      yPosition += 30;

      // Prescription Title
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(this.HEADER_COLOR);
      pdf.text('MEDICAL PRESCRIPTION', pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;

      // Prescription ID and Date
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(this.TEXT_COLOR);
      pdf.text(`Prescription ID: ${prescription.id}`, margin, yPosition);
      pdf.text(`Date: ${new Date(prescription.createdAt).toLocaleDateString()}`, pageWidth - margin - 50, yPosition);
      yPosition += 15;

      // Doctor Information
      yPosition = this.addDoctorInfo(pdf, doctor, margin, yPosition, pageWidth);
      yPosition += 10;

      // Patient Information
      yPosition = this.addPatientInfo(pdf, patient, margin, yPosition, pageWidth);
      yPosition += 10;

      // Diagnosis and Symptoms
      yPosition = this.addDiagnosisInfo(pdf, prescription, margin, yPosition, pageWidth);
      yPosition += 10;

      // Medications
      yPosition = this.addMedicationsTable(pdf, prescription, margin, yPosition, pageWidth);
      yPosition += 15;

      // Doctor's Notes
      if (prescription.notes) {
        yPosition = this.addNotesSection(pdf, prescription.notes, margin, yPosition, pageWidth);
        yPosition += 15;
      }

      // Digital Signature
      if (signature) {
        yPosition = this.addDigitalSignature(pdf, signature, margin, yPosition, pageWidth);
      }

      // Footer
      this.addFooter(pdf, pageWidth, pageHeight, margin);

      // Add watermark
      this.addWatermark(pdf, pageWidth, pageHeight);

      // Download the PDF
      const fileName = `Prescription_${prescription.id}_${patient.name?.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
      pdf.save(fileName);

    } catch (error) {
      console.error('Error generating PDF:', error);
      throw new Error('Failed to generate prescription PDF');
    }
  }

  static async generatePatientSummaryPDF(
    patient: Patient,
    prescriptions: Prescription[],
    doctor: Doctor
  ): Promise<void> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.width;
    const margin = 20;
    let yPosition = margin;

    // Header
    this.addHeader(pdf, pageWidth, margin, yPosition);
    yPosition += 30;

    // Title
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(this.HEADER_COLOR);
    pdf.text('PATIENT MEDICAL SUMMARY', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // Generated by
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(this.TEXT_COLOR);
    pdf.text(`Generated by: Dr. ${doctor.name}`, margin, yPosition);
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin, yPosition, { align: 'right' });
    yPosition += 15;

    // Patient Info
    yPosition = this.addPatientInfo(pdf, patient, margin, yPosition, pageWidth);
    yPosition += 10;

    // Allergies and Medical History
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Allergies:', margin, yPosition);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(patient.allergies.join(', ') || 'None reported', margin + 30, yPosition);
    yPosition += 8;

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Medical History:', margin, yPosition);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(patient.medicalHistory.join(', ') || 'None reported', margin + 40, yPosition);
    yPosition += 15;

    // Prescription History
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Prescription History', margin, yPosition);
    yPosition += 8;

    prescriptions.forEach(p => {
      if (yPosition > pdf.internal.pageSize.height - 40) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.setDrawColor(200);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 8;
      
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`Diagnosis: ${p.diagnosis}`, margin, yPosition);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Date: ${new Date(p.createdAt).toLocaleDateString()}`, pageWidth - margin, yPosition, { align: 'right' });
      yPosition += 6;
      pdf.text(`Prescribed by: Dr. ${p.doctorName}`, margin, yPosition);
      yPosition += 8;

      this.addMedicationsTable(pdf, p, margin, yPosition, pageWidth, false);
      yPosition = (pdf as any).lastAutoTable.finalY + 10;
    });

    // Footer
    this.addFooter(pdf, pdf.internal.pageSize.width, pdf.internal.pageSize.height, margin);

    // Download
    const fileName = `PatientSummary_${patient.name?.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
    pdf.save(fileName);
  }

  private static addHeader(pdf: jsPDF, pageWidth: number, margin: number, yPosition: number): void {
    // Logo and System Name
    pdf.setFillColor(30, 64, 175); // Header color
    pdf.rect(0, 0, pageWidth, 25, 'F');
    
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(255, 255, 255);
    pdf.text(this.LOGO_TEXT, pageWidth / 2, 15, { align: 'center' });
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Advanced Antibiotic Tracking & Healthcare Management System', pageWidth / 2, 20, { align: 'center' });
  }

  private static addDoctorInfo(pdf: jsPDF, doctor: Doctor, margin: number, yPosition: number, pageWidth: number): number {
    pdf.setFillColor(240, 249, 255);
    pdf.rect(margin, yPosition, pageWidth - (margin * 2), 25, 'F');
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(this.HEADER_COLOR);
    pdf.text('PRESCRIBING PHYSICIAN', margin + 5, yPosition + 8);
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(this.TEXT_COLOR);
    pdf.text(`Dr. ${doctor.name}`, margin + 5, yPosition + 15);
    pdf.text(`Specialty: ${doctor.specialty}`, margin + 5, yPosition + 20);
    pdf.text(`License: ${doctor.licenseNumber}`, pageWidth - margin - 60, yPosition + 15);
    
    return yPosition + 25;
  }

  private static addPatientInfo(pdf: jsPDF, patient: Patient, margin: number, yPosition: number, pageWidth: number): number {
    pdf.setFillColor(248, 250, 252);
    pdf.rect(margin, yPosition, pageWidth - (margin * 2), 30, 'F');
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(this.HEADER_COLOR);
    pdf.text('PATIENT INFORMATION', margin + 5, yPosition + 8);
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(this.TEXT_COLOR);
    
    pdf.text(`Name: ${patient.name || 'N/A'}`, margin + 5, yPosition + 15);
    pdf.text(`Age: ${patient.age || 'N/A'} years`, margin + 5, yPosition + 20);
    const genderText = patient.gender ? `${patient.gender.charAt(0).toUpperCase()}${patient.gender.slice(1)}` : 'N/A';
    pdf.text(`Gender: ${genderText}`, margin + 5, yPosition + 25);
    
    pdf.text(`Patient ID: ${patient.id}`, pageWidth - margin - 60, yPosition + 15);
    pdf.text(`Phone: ${patient.phoneNumber}`, pageWidth - margin - 60, yPosition + 20);
    
    // Allergies warning if present
    if (patient.allergies && patient.allergies.length > 0) {
      pdf.setTextColor(this.ACCENT_COLOR);
      pdf.setFont('helvetica', 'bold');
      pdf.text('⚠ ALLERGIES:', margin + 5, yPosition + 32);
      pdf.setFont('helvetica', 'normal');
      pdf.text(patient.allergies.join(', '), margin + 25, yPosition + 32);
    }
    
    return yPosition + (patient.allergies && patient.allergies.length > 0 ? 35 : 30);
  }

  private static addDiagnosisInfo(pdf: jsPDF, prescription: Prescription, margin: number, yPosition: number, pageWidth: number): number {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(this.HEADER_COLOR);
    pdf.text('DIAGNOSIS & SYMPTOMS', margin, yPosition);
    yPosition += 8;
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(this.TEXT_COLOR);
    pdf.text(`Diagnosis: ${prescription.diagnosis}`, margin, yPosition);
    yPosition += 6;
    
    if (prescription.symptoms && prescription.symptoms.length > 0) {
      pdf.text(`Symptoms: ${prescription.symptoms.join(', ')}`, margin, yPosition);
      yPosition += 6;
    }
    
    return yPosition;
  }

  private static addMedicationsTable(pdf: jsPDF, prescription: Prescription, margin: number, yPosition: number, pageWidth: number, includeHeader: boolean = true): number {
    const tableHeaders = [['Medication', 'Dosage', 'Quantity', 'Frequency', 'Duration', 'Route', 'Indication']];
    const tableBody = prescription.medications.map(med => [
      med.medication.name,
      med.dosage,
      med.quantity ? med.quantity.toString() : 'N/A',
      med.frequency,
      med.duration,
      med.route || 'N/A',
      med.indication || 'N/A'
    ]);

    autoTable(pdf, {
      head: includeHeader ? tableHeaders : undefined,
      body: tableBody,
      startY: yPosition,
      theme: 'grid',
      headStyles: {
        fillColor: this.HEADER_COLOR,
        textColor: 255,
        fontStyle: 'bold'
      },
      styles: {
        cellPadding: 2,
        fontSize: 9,
        textColor: this.TEXT_COLOR
      },
      margin: { left: margin, right: margin }
    });

    return (pdf as any).lastAutoTable.finalY;
  }

  private static addNotesSection(pdf: jsPDF, notes: string, margin: number, yPosition: number, pageWidth: number): number {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(this.HEADER_COLOR);
    pdf.text('DOCTOR\'S NOTES', margin, yPosition);
    yPosition += 8;
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(this.TEXT_COLOR);
    
    const maxWidth = pageWidth - (margin * 2);
    const lines = pdf.splitTextToSize(notes, maxWidth);
    pdf.text(lines, margin, yPosition);
    
    return yPosition + (lines.length * 4);
  }

  private static addDigitalSignature(pdf: jsPDF, signature: DigitalSignature, margin: number, yPosition: number, pageWidth: number): number {
    // Green background box
    pdf.setFillColor(240, 255, 240);
    pdf.rect(margin, yPosition, pageWidth - (margin * 2), 55, 'F');
    
    // Title
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 128, 0);
    pdf.text('✓ DIGITALLY SIGNED', margin + 5, yPosition + 8);
    
    // Doctor details (left side)
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(this.TEXT_COLOR);
    pdf.text(`Signed by: Dr. ${signature.doctorName}`, margin + 5, yPosition + 18);
    pdf.text(`License: ${signature.licenseNumber}`, margin + 5, yPosition + 24);
    pdf.text(`Date: ${signature.signatureDate}`, margin + 5, yPosition + 30);
    
    // Add the actual signature IMAGE if available
    if (signature.digitalCertificate) {
      try {
        // The digitalCertificate contains the base64 image data
        const signatureWidth = 50;
        const signatureHeight = 20;
        const signatureX = pageWidth - margin - signatureWidth - 5;
        const signatureY = yPosition + 15;
        
        // Add signature image to PDF
        pdf.addImage(signature.digitalCertificate, 'PNG', signatureX, signatureY, signatureWidth, signatureHeight);
        
        // Add label above signature
        pdf.setFontSize(8);
        pdf.setTextColor(100, 100, 100);
        pdf.text('Doctor\'s Signature:', signatureX, signatureY - 2);
      } catch (error) {
        console.error('Error adding signature image:', error);
        // Fallback text if image fails
        pdf.text('Signature: [Digital]', pageWidth - margin - 60, yPosition + 25);
      }
    }
    
    // Verification text
    pdf.setFontSize(8);
    pdf.setTextColor(this.TEXT_COLOR);
    pdf.text('This prescription is digitally signed and verified.', margin + 5, yPosition + 42);
    pdf.text('Certificate ID: LX-ALT-' + Date.now().toString(36).toUpperCase(), margin + 5, yPosition + 48);
    
    return yPosition + 55;
  }

  private static addFooter(pdf: jsPDF, pageWidth: number, pageHeight: number, margin: number): void {
    const footerY = pageHeight - 15;
    
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(128, 128, 128);
    
    pdf.text('Generated by LuminaX-alt Antibiotic Tracking System', pageWidth / 2, footerY, { align: 'center' });
    pdf.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, footerY + 4, { align: 'center' });
    pdf.text('This is a computer-generated prescription. Valid only with digital signature.', pageWidth / 2, footerY + 8, { align: 'center' });
  }

  private static addWatermark(pdf: jsPDF, pageWidth: number, pageHeight: number): void {
    pdf.setTextColor(240, 240, 240);
    pdf.setFontSize(40);
    pdf.setFont('helvetica', 'bold');
    
    // Save the current transformation matrix
    pdf.saveGraphicsState();
    
    // Translate to center and rotate
    pdf.setGState(pdf.GState({ opacity: 0.1 }));
    pdf.text('LuminaX-alt', pageWidth / 2, pageHeight / 2, { 
      align: 'center',
      angle: 45
    });
    
    // Restore the graphics state
    pdf.restoreGraphicsState();
  }

  static async generatePrescriptionFromElement(elementId: string): Promise<void> {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error('Element not found');
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        allowTaint: false
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgX = (pdfWidth - imgWidth * ratio) / 2;
      const imgY = 30;

      pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth * ratio, imgHeight * ratio);
      pdf.save(`Prescription_${Date.now()}.pdf`);
    } catch (error) {
      console.error('Error generating PDF from element:', error);
      throw new Error('Failed to generate PDF from element');
    }
  }
}
